name: My First workflow

on: push

jobs: 
  first_job:
    runs-on: ubuntu:latest
    steps: 
      - name: Checkout 
        uses: actions/checkout@v4
      - name: List and read file
        run: |
             echo "Updated the first github action"
             ls
             cat README.md