name: Generate ASCII Artwork

on: 
   push
jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Code
          uses: actions/checkout@v4
        - name: Listing the files in repo
          run: ls -ltra
        - name: Running the Shell Script with error fixed
          run: |
              chmod +x ascii-script.sh
              ./ascii-script.sh
            