name: Generate ASCII Artwork

on: 
   push
jobs:
    ascii-job:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Action
          uses: actions/checkout@v4
        - name: Listing the files in repo
          run: ls
        - name: Running the Script
          run: |
              chmod +x ascii-script.sh
              ./ascii-script.sh
            